version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    restart: always
    ports:
      - '80:80'